// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go

// Package versionedcache is a generated GoMock package.
package versionedcache

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// Mockdriver is a mock of driver interface.
type Mockdriver struct {
	ctrl     *gomock.Controller
	recorder *MockdriverMockRecorder
}

// MockdriverMockRecorder is the mock recorder for Mockdriver.
type MockdriverMockRecorder struct {
	mock *Mockdriver
}

// NewMockdriver creates a new mock instance.
func NewMockdriver(ctrl *gomock.Controller) *Mockdriver {
	mock := &Mockdriver{ctrl: ctrl}
	mock.recorder = &MockdriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdriver) EXPECT() *MockdriverMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *Mockdriver) Clear(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockdriverMockRecorder) Clear(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*Mockdriver)(nil).Clear), ctx, key)
}

// Get mocks base method.
func (m *Mockdriver) Get(ctx context.Context, key string, deserializer func(context.Context, []byte) (interface{}, error)) (interface{}, bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, deserializer)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Get indicates an expected call of Get.
func (mr *MockdriverMockRecorder) Get(ctx, key, deserializer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockdriver)(nil).Get), ctx, key, deserializer)
}

// MGet mocks base method.
func (m *Mockdriver) MGet(ctx context.Context, keys []string, deserializer func(context.Context, []byte) (interface{}, error)) (map[string]interface{}, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MGet", ctx, keys, deserializer)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MGet indicates an expected call of MGet.
func (mr *MockdriverMockRecorder) MGet(ctx, keys, deserializer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*Mockdriver)(nil).MGet), ctx, keys, deserializer)
}

// Set mocks base method.
func (m *Mockdriver) Set(ctx context.Context, key string, item interface{}, serializer func(context.Context, interface{}) ([]byte, error), expiration, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, item, serializer, expiration, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockdriverMockRecorder) Set(ctx, key, item, serializer, expiration, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*Mockdriver)(nil).Set), ctx, key, item, serializer, expiration, ttl)
}

// Mocklocker is a mock of locker interface.
type Mocklocker struct {
	ctrl     *gomock.Controller
	recorder *MocklockerMockRecorder
}

// MocklockerMockRecorder is the mock recorder for Mocklocker.
type MocklockerMockRecorder struct {
	mock *Mocklocker
}

// NewMocklocker creates a new mock instance.
func NewMocklocker(ctrl *gomock.Controller) *Mocklocker {
	mock := &Mocklocker{ctrl: ctrl}
	mock.recorder = &MocklockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklocker) EXPECT() *MocklockerMockRecorder {
	return m.recorder
}

// LockKey mocks base method.
func (m *Mocklocker) LockKey(ctx context.Context, key string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockKey", ctx, key, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockKey indicates an expected call of LockKey.
func (mr *MocklockerMockRecorder) LockKey(ctx, key, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockKey", reflect.TypeOf((*Mocklocker)(nil).LockKey), ctx, key, ttl)
}
