version: '3.4'
services:
  redis-cluster:
    image: "grokzen/redis-cluster:latest"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    environment:
      IP: 0.0.0.0